#!/usr/bin/env bash

OUTPUT='';
BLUETOOTH_DEFAULTS=$(defaults read /Library/Preferences/com.apple.Bluetooth);
SYSTEM_PROFILER=$(system_profiler SPBluetoothDataType 2>/dev/null)
MAC_ADDR=$(grep -b2 "Minor Type: Headphones"<<<"${SYSTEM_PROFILER}"|awk '/Address/{print $3}')
CONNECTED=$(grep -ia6 "${MAC_ADDR}"<<<"${SYSTEM_PROFILER}"|awk '/Connected: Yes/{print 1}')
BLUETOOTH_DATA=$(grep -ia6 '"'"${MAC_ADDR}"'"'<<<"${BLUETOOTH_DEFAULTS}")
BATTERY_LEVELS=("BatteryPercentLeft" "BatteryPercentRight")

if [[ "${CONNECTED}" ]]; then
    for I in "${BATTERY_LEVELS[@]}"; do
        declare -x "${I}"="$(awk -v pat="${I}" '$0~pat{gsub (";",""); print $3 }'<<<"${BLUETOOTH_DATA}")"
        [[ ! -z "${!I}" ]] && OUTPUT="${OUTPUT} $(awk '/BatteryPercent/{print substr($0,15,1)": "}'<<<"${I}")${!I}%"
    done

    battery=$(echo $OUTPUT | awk '{
        l = "";
        r = "";
        for (i = 1; i < NF; i++) {
          if ($i == "L:") {l = $(i + 2);}
          else if ($i == "R:") {r = $(i + 2);}
        } 
        print "L: " l, "R: " r
      }')
    arg=1;
    subtitle="Press Enter to disconnect";
else
    battery="Not Connected"
    arg=0;
    subtitle="Press Enter to connect";
fi

cat << EOB
{"items": [
    {
        "uid": "battery",
        "title": "$battery",
        "subtitle": "$subtitle",
        "arg": "$arg",
    }
]}
EOB
